import React from 'react';
import LocalizedStrings from 'react-native-localization';
import { Image, View, ImageBackground, AsyncStorage} from 'react-native';
// this.setState({
//     langi:await AsyncStorage.getItem('language')
//   })
const strings = new LocalizedStrings({
    en:{
        
        lets:"Let's Go",
        home: "Home",
        sign:"Sign In",
        term:"Terms & Conditions",
        our:"Our Services to Our Partners",
        why:"Why TinyLand",
        Contact:"Contact Us",
        all:"All",
        bilingual:"Bilingual",
        islamic:"Islamic",
        trilingual:"Trilingual Nursery",
        Special:"Special Needs",
        seven:"Seven Petal Education",
        montessori:"Montessori Curriculum",
        vacant:"Vacant",
        registrationOpen:"Registration Open",
        near:"Near By",
        Nurseries:"Nurseries",
        searchnurseries:"Search Nurseries",
        about:"About Us",
        subscription:"Subscription",
        event:"Event & Activities",
        management: "Management",
        number:"Number Of",
        supervisers: "Supervisers",
        teachers: "Teachers",
        methodology:"Methodology",
        subscribe:"Subscribe",
        download:"Download",
        paypal: "PayPal",
        stripe: "Stripe",
        subscribeno:"Subscribe Number",
        idnumber: "ID Number",
        phone: "Phone Number",
        area: "Area",
        createorder: "Create Order",
        email: "Email ID",
        password: "password",
        forgot: "Forgot Password",
        signup: "Sign Up",
        signin: "Sign In",
        first: "First Name",
        last: "Last Name",
        emailid: "Email ID",
        confirm: "Confirm Password",
        submit: "Submit",
        mypro: "My Profile",
        changepass: "Change Password",
        logout: "Log Out",
        opass: "Old Password",
        npass:"New Password",
        typeverification: "Please type the verification code sent to your Email.",
        wrongotp: "You entered wrong otp. Try again",
        vfcode: "A Verification Code sent to your email id please enter the code to under given text box to complete your registration"
        
      },
  
"ar":{
    
    lets:"لنذهب",
    home: "الصفحة الرئيسية",
    sign:"تسجيل الدخول",
    term:"البنود و الظروف",
    our:"خدماتنا لشركائنا",
    why:"لماذا TinyLand",
    Contact:"اتصل بنا",
    all:"الكل",
    bilingual:"ثنائي اللغة",
    islamic:"الإسلامية",
    trilingual:"حضانة ثلاثية اللغات",
    Special:"الاحتياجات الخاصة",
    seven:"سبعة بتلة التعليم",
    montessori:"منهج مونتيسوري",
    vacant:"شاغر",
    registrationOpen:"فتح التسجيل",
    near:"مجاور",
    Nurseries:"مشاتل",
    searchnurseries:"بحث الحضانات",
    about:"معلومات عنا",
    subscription:"اشتراك",
    event:"الحدث والأنشطة",
    management: "Management",
    number:"رقم ال",
    supervisers: "المشرفين",
    teachers: "معلمون",
    methodology:"منهجية",
    subscribe:"الإشتراك",
    download:"تحميل",
    paypal: "باي بال",
    stripe: "شريط",
    subscribeno:"رقم الاشتراك",
    idnumber: "رقم الهوية",
    phone: "رقم الهاتف",
    area: "منطقة",
    createorder: "إنشاء النظام",
    email: "البريد الإلكتروني",
    password: "كلمه السر",
    forgot: "هل نسيت كلمة المرور",
    signup: "سجل",
    signin: "تسجيل الدخول",
    first: "الاسم الاول",
    last: "الكنية",
    emailid: "عنوان الايميل",
    confirm: "تأكيد كلمة المرور",
    submit: "إرسال",
    mypro: "ملفي",
    changepass: "تغيير كلمة السر",
    logout: "تسجيل خروج",
    opass: "كلمة سر قديمة",
    npass:"كلمة مرور جديدة",
    typeverification: "يرجى كتابة رمز التحقق الذي تم إرساله إلى بريدك الإلكتروني.",
    wrongotp: "لقد دخلت otp خاطئ. حاول مجددا",
    vfcode: "تم إرسال رمز التحقق إلى معرف البريد الإلكتروني الخاص بك ، يرجى إدخال الرمز أسفل مربع النص المحدد لإكمال التسجيل"
  }
});
export default strings;